version: '3'
services:
  mock-api:
    build: ../Server
    image: secbyte/mockapi:v2.5
    environment:
      - DataSource=local:./data
      - RoutesFile=routes.json
    volumes:
      - "../Server/data:/app/data"
    ports:
      - "4000:80"
